apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: unshorten-api-ingress
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: unshortenit.info
    http:
      paths:
      - path: /
        backend:
          serviceName: link-unshorten-service
          servicePort: 80