kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: jenkins-limited
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["create", "list", "update", "watch"]
- apiGroups: ["extensions", "apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]


