kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: link-unshorten-clusterrole
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - restrict-root