# Bind the ClusterRole to the desired set of service accounts.
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: link-unshorten-clusterrolebinding
roleRef:
  kind: ClusterRole
  name: link-unshorten-clusterrolebinding
  apiGroup: rbac.authorization.k8s.io
subjects:
# All authenticated users are bound
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:authenticated