apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: gce
  name: link-unshorten-ingress
spec:
  backend:
    serviceName: link-unshorten-service
    servicePort: 80
