apiVersion: apps/v1
kind: Deployment
metadata:
  name: link-unshorten-non-root
  labels:
    app: unshorten-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unshorten-api
  template: 
    metadata:
      labels:
        app: unshorten-api
    spec:
      securityContext:
        runAsUser: 999
      volumes:
      - name: i-need-this-volume
        hostPath:
          path: /etc/passwd
          type: File
      containers:
      - name: unshorten-api-container
        image: "jmbmxer/link-unshorten:0.1"
        imagePullPolicy: Always
        volumeMounts:
        - name: i-need-this-volume
          mountPath: /go/src/unshorten-api
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP