apiVersion: v1
kind: Service
metadata:
 name: unshorten-api
 namespace: unshorten-prod
spec:
 type: NodePort
 ports:
   - port: 80
     targetPort: 8080
     protocol: TCP
 selector:
   app: unshorten-api