apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: unshorten-api
    env: prod
  name: unshorten-api
  namespace: unshorten-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unshorten-api
      env: prod
  template: 
    metadata:
      labels:
        app: unshorten-api
        env: prod
    spec:
      containers:
      - name: unshorten-api-container
        image: "jmbmxer/link-unshorten:0.1"
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /healthz/
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 15
          timeoutSeconds: 1
        livenessProbe:
          httpGet:
            path: /healthz/
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
      restartPolicy: Always