kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv0001
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/jb0ss/Desktop/Defending-DevOps-Training/labs/5-K8S-Cluster-Secrets/data"