kind: Config
apiVersion: v1
clusters:
  - name: requestbin
    cluster:
      server: <your.internal.logging.service>
contexts:
- name: webhook
  context:
    cluster: requestbin
current-context: webhook