# This cluster role binding allows the reading of secrets in the development namespace
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: read-secrets-development
  namespace: development
subjects:
- kind: User
  name: jboss
  apiGroup: ""
roleRef:
  kind: Role
  name: secret-reader
  apiGroup: ""